"""Refactor Tasks

Revision ID: 0f5598317406
Revises: 427bf5ceec3b
Create Date: 2016-02-03 23:24:20.640494

"""

# revision identifiers, used by Alembic.
revision = '0f5598317406'
down_revision = '427bf5ceec3b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('closed_date', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'is_checked')
    op.drop_column('tasks', 'checked_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('checked_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('is_checked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'closed_date')
    ### end Alembic commands ###
