"""Added Cascading to Relationships

Revision ID: 10b50c4d2c65
Revises: 10c695123c4d
Create Date: 2015-12-15 05:19:48.929463

"""

# revision identifiers, used by Alembic.
revision = '10b50c4d2c65'
down_revision = '10c695123c4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'roles_pkey'),
    sa.UniqueConstraint('name', name=u'roles_name_key')
    )
    ### end Alembic commands ###
