"""Added favorites column to notes

Revision ID: 10c695123c4d
Revises: 4c1fb76895a6
Create Date: 2015-12-09 04:40:23.995528

"""

# revision identifiers, used by Alembic.
revision = '10c695123c4d'
down_revision = '4c1fb76895a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('roles')
    op.add_column('notes', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_notes_created_date'), 'notes', ['created_date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_created_date'), table_name='notes')
    op.drop_column('notes', 'is_favorite')
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'roles_pkey'),
    sa.UniqueConstraint('name', name=u'roles_name_key')
    )
    ### end Alembic commands ###
