"""empty message

Revision ID: 22ff176f7d50
Revises: None
Create Date: 2015-11-25 10:43:14.350295

"""

# revision identifiers, used by Alembic.
revision = '22ff176f7d50'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_date')
    op.drop_column('users', 'created_date')
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
