"""empty message

Revision ID: 34f650d1a028
Revises: None
Create Date: 2015-11-22 17:43:18.053592

"""

# revision identifiers, used by Alembic.
revision = '34f650d1a028'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    ### end Alembic commands ###
