"""removed sections

Revision ID: 34fa673d7905
Revises: 49813a862bbf
Create Date: 2015-12-06 20:26:46.537729

"""

# revision identifiers, used by Alembic.
revision = '34fa673d7905'
down_revision = '49813a862bbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'notes_section_id_fkey', 'notes', type_='foreignkey')
    op.drop_column('notes', 'section_id')
    op.drop_table('sections')
    op.add_column('notes', sa.Column('notebook_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'notebooks', ['notebook_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(u'notes_section_id_fkey', 'notes', 'sections', ['section_id'], ['id'])
    op.drop_column('notes', 'notebook_id')
    op.create_table('sections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('notebook_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notebook_id'], [u'notebooks.id'], name=u'sections_notebook_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'sections_pkey')
    )
    ### end Alembic commands ###
