"""empty message

Revision ID: 418d1a88e9ae
Revises: None
Create Date: 2015-11-22 18:38:51.430376

"""

# revision identifiers, used by Alembic.
revision = '418d1a88e9ae'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'body_html')
    ### end Alembic commands ###
