"""first migration

Revision ID: 427bf5ceec3b
Revises: None
Create Date: 2016-02-03 21:16:15.256372

"""

# revision identifiers, used by Alembic.
revision = '427bf5ceec3b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_items')
    op.add_column('tasks', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'tasks_note_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(u'tasks_note_id_fkey', 'tasks', 'notes', ['note_id'], ['id'])
    op.drop_column('tasks', 'author_id')
    op.create_table('todo_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('is_checked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('checked_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['note_id'], [u'notes.id'], name=u'todo_items_note_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'todo_items_pkey')
    )
    ### end Alembic commands ###
