"""first migration

Revision ID: 4314736392d3
Revises: None
Create Date: 2015-12-06 07:11:17.232624

"""

# revision identifiers, used by Alembic.
revision = '4314736392d3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notebooks', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notebooks', type_='foreignkey')
    op.drop_column('notebooks', 'author_id')
    ### end Alembic commands ###
