"""Added deleted column to Notebook

Revision ID: 49813a862bbf
Revises: 4314736392d3
Create Date: 2015-12-06 07:12:44.697606

"""

# revision identifiers, used by Alembic.
revision = '49813a862bbf'
down_revision = '4314736392d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebooks', 'is_deleted')
    ### end Alembic commands ###
