"""add default notebook to users

Revision ID: 55c778dd35ab
Revises: c052ae5abc1d
Create Date: 2016-12-17 21:24:03.788486

"""

# revision identifiers, used by Alembic.
revision = '55c778dd35ab'
down_revision = 'c052ae5abc1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_notebook', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_notebook')
    # ### end Alembic commands ###
