"""Add Created and Updated date to Notebook

Revision ID: 5d3c326dd901
Revises: 3a37e844b277
Create Date: 2016-08-29 10:39:23.609605

"""

# revision identifiers, used by Alembic.
revision = '5d3c326dd901'
down_revision = '3a37e844b277'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('notebooks', sa.Column('updated_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebooks', 'updated_date')
    op.drop_column('notebooks', 'created_date')
    ### end Alembic commands ###
