"""Added Task to Notebook

Revision ID: 6ad7d8feaa75
Revises: 0f5598317406
Create Date: 2016-02-04 00:34:46.465667

"""

# revision identifiers, used by Alembic.
revision = '6ad7d8feaa75'
down_revision = '0f5598317406'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('notebook_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'notebooks', ['notebook_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'notebook_id')
    ### end Alembic commands ###
