"""Update User model, remove username, add first and lastname

Revision ID: b237b9f6a2ce
Revises: 3b4b395f61a9
Create Date: 2016-05-12 18:42:21.473162

"""

# revision identifiers, used by Alembic.
revision = 'b237b9f6a2ce'
down_revision = '3b4b395f61a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=200), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    ### end Alembic commands ###
