"""Remove html_body from notes

Revision ID: c052ae5abc1d
Revises: ffe4c66b5772
Create Date: 2016-08-30 10:59:26.263398

"""

# revision identifiers, used by Alembic.
revision = 'c052ae5abc1d'
down_revision = 'ffe4c66b5772'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'body_html')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('body_html', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
