"""Add Shared Notes

Revision ID: ffe4c66b5772
Revises: 5d3c326dd901
Create Date: 2016-08-30 08:40:35.993215

"""

# revision identifiers, used by Alembic.
revision = 'ffe4c66b5772'
down_revision = '5d3c326dd901'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(length=254), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_notes_created_date'), 'shared_notes', ['created_date'], unique=False)
    op.create_index(op.f('ix_shared_notes_updated_date'), 'shared_notes', ['updated_date'], unique=False)
    op.add_column('users', sa.Column('last_login_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_date')
    op.drop_index(op.f('ix_shared_notes_updated_date'), table_name='shared_notes')
    op.drop_index(op.f('ix_shared_notes_created_date'), table_name='shared_notes')
    op.drop_table('shared_notes')
    ### end Alembic commands ###
